# Configuraiton information: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# and: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
# To find the default files for the theme: 
# bundle info minimal-mistakes-jekyll.

# Site Settings
locale                   : "en-US"
title: Ractor
title_separator: "|"
# email: slawlor
description: >- # this means to ignore newlines until "baseurl:"
  Ractor provides a fully-supervised, tokio-friendly actor framework
  for Rust frameworks. It is modelled closely off of Erlang's gen_server
  along with extensions such as factories and distributed clusters.
baseurl: "/ractor" # the subpath of your site, e.g. /blog
url: "https://slawlor.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: slawlor/ractor
logo: "/assets/images/ractor_logo.svg"
masthead_title: "Ractor - actors for Rust"
subtitle: "Built on Tokio"
# search: true
atom_feed:
  hide: true
twitter:
  username: shiggschili

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
lunr:
  search_within_pages: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/shiggschili"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/slawlor"

include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true