[package]
name = "ractor"
version = "0.9.3"
authors = ["Sean Lawlor", "Evan Au", "Dillon George"]
description = "A actor framework for Rust"
documentation = "https://docs.rs/ractor"
license = "MIT"
edition = "2021"
keywords = ["actor", "ractor"]
repository = "https://github.com/slawlor/ractor"
readme = "../README.md"
homepage = "https://github.com/slawlor/ractor"
categories = ["actor", "erlang"]
rust-version = "1.64"

[features]
### Other features
cluster = []

default = []

[dependencies]
## Required dependencies
async-trait = "0.1"
dashmap = "5"
futures = "0.3"
once_cell = "1"

# Tracing feature requires --cfg=tokio_unstable
tokio = { version = "1", features = ["sync", "time", "rt", "macros", "tracing"] }
async-std = { version = "1", features = ["attributes"], optional = true}
tracing = { version = "0.1", features = ["attributes"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# TODO #124 - this is due to the temporary disabling of the "factory" module
rand = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# instant = { version = "0.1", features = ["wasm-bindgen"]}
getrandom = { version = "0.2", features = ["js"] }
parking_lot = { version = "0.11", features = ["wasm-bindgen"] }
wasm-timer = { version = "0.2" }
wasm-bindgen-futures = { version = "0.4"}
wasm-bindgen-test = "0.3"
wasmtimer = { version = "0.2", features = ["tokio"] }

[dev-dependencies]
backtrace = "0.3"
function_name = "0.3"
paste = "1"
rand = "0.8"
tracing-glog = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1"
tokio = { version = "1", features = ["rt", "time", "sync", "macros"] }
tracing-wasm = "0.2"
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.5"
tokio = { version = "1", features = ["rt", "time", "sync", "macros", "rt-multi-thread", "tracing"] }
tracing-test = "0.2"


[[bench]]
name = "actor"
harness = false
required-features = []
